---
- hosts: redis-master
  tasks:
    - debug:
        msg: "{{ ansible_default_ipv4.address }}"
  become: false
  become_user: root
  become_method: sudo
  roles:
    - role: redis-master

- hosts: redis-slave
  become: false
  become_user: root
  become_method: sudo
  roles:
    - role: redis-slave
